# Climate 

# Climate Mansarda
- platform: generic_thermostat
  name: loft
  heater: switch.loft_thermostat
  target_sensor: sensor.loft_relevant_temperature
  min_temp: 16
  max_temp: 32
  target_temp: 19.5
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  ac_mode: false
  precision: 0.1
