# Climate 

# Climate Loft
- platform: generic_thermostat
  name: loft
  heater: switch.loft_thermostat
  target_sensor: sensor.loft_relevant_temperature
  min_temp: 16
  max_temp: 32
  target_temp: 19.5
  cold_tolerance: 0.2
  hot_tolerance: 0.1
  ac_mode: false
  precision: 0.1

# Climate Main
- platform: generic_thermostat
  name: main
  heater: switch.main_thermostat
  target_sensor: sensor.0x00158d0003cd2888_temperature
  min_temp: 16
  max_temp: 32
  target_temp: 17
  cold_tolerance: 0.2
  hot_tolerance: 0.1
  ac_mode: false
  precision: 0.1