# Main Configuration File

# Homeassistant
homeassistant:
  name: "Home CDB"
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include customize.yaml

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 75

# Basic Functionality
#cloud:
config:
counter:
dhcp:
energy:
frontend:
image:
map:
media_source:
mobile_app:
my:
person:
ssdp:
#stream:
system_health:
tag:
timer:
updater:
usb:
webhook:
zeroconf:

# Http
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.252
    - 127.0.0.1

# Split Config 1
recorder: !include recorder.yaml
history:
logbook:

# Split Config 2
automation: !include_dir_merge_list automation
climate: !include climates.yaml
sensor: !include_dir_merge_list sensor
script: !include_dir_merge_named ./script
switch: !include_dir_merge_list switch
#group:
#scene:

# Utility Meter
utility_meter:
  home_consumption_daily:
    source: sensor.home_consumption
    name: Consumo Casa Giornaliero
    cycle: daily
  home_consumption_monthly:
    source: sensor.home_consumption
    name: Consumo Casa Mensile
    cycle: monthly
  tavern_and_garage_consumption_daily:
    source: sensor.tavern_and_garage_consumption
    name: Consumo Taverna&Garage Giornaliero
    cycle: daily
  tavern_and_garage_consumption_monthly:
    source: sensor.tavern_and_garage_consumption
    name: Consumo Taverna&Garage Mensile
    cycle: monthly
  loft_and_main_consumption_daily:
    source: sensor.loft_and_main_consumption
    name: Consumo Loft&Main Giornaliero
    cycle: daily
  loft_and_main_consumption_monthly:
    source: sensor.loft_and_main_consumption
    name: Consumo Loft&Main Mensile
    cycle: monthly

# Interface
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js
      type: module

# Driver & Camera
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# Weather
sun:

weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

# Google Assistant
google_assistant:
  project_id: hassos-2020f
  service_account: !include hassos-2020f-a212bf5e55ff.json
  report_state: true
  expose_by_default: false
  exposed_domains:
    - switch
    - climate
  entity_config:
    switch.shellyswitch25_740859_channel_1:
      name: Ingresso
      expose: true
    switch.shellyswitch25_740859_channel_2:
      name: Cucina
      expose: true
    switch.shellyswitch25_740826_channel_2:
      name: Salotto
      expose: true
    switch.shelly1pm_e09806a9efcf:
      name: Aba
      expose: true
    switch.shellyswitch25_740826_channel_1:
      name: Camera
      expose: true
    switch.shellyswitch_55c794_channel_2:
      name: Faretti
      expose: true
    switch.shellyswitch_55c794_channel_1:
      name: Studio
      expose: true
    switch.shelly1pm_84cca8a855b6:
      name: Albero
      expose: true
    switch.shellyswitch_55c39a_channel_2:
      name: Tana
      expose: true
    switch.shellyswitch_55c39a_channel_1:
      name: Cielo
      expose: true
    switch.shellyswitch_559384_channel_2:
      name: Scaffale
      expose: true
    sensor.shellyswitch_559384_power:
      name: DiscoBall
      expose: true
    switch.shelly1_5551cc:
      name: Cancello
      expose: true
    input_boolean.radio_activate:
      name: Radio
      expose: true
    input_boolean.loft_discoball_activate:
      name: Party
      expose: true

      # TTS
tts:
  - platform: google_translate
    service_name: google_say
    language: it

# Binary Sensor
binary_sensor:
  # Computer
  - platform: ping
    name: K9
    host: !secret ip_k9
    scan_interval: 300
  - platform: ping
    name: K4
    host: !secret ip_k4
    scan_interval: 300
  # Devices
  - platform: ping
    name: RM Mini
    host: !secret ip_rmmini
    scan_interval: 300
  - platform: ping
    name: Yi Camera
    host: !secret ip_yicamera
    scan_interval: 300
  - platform: mqtt
    name: Pir Yi
    state_topic: "yicam/motion"
    payload_on: "motion_start"
    payload_off: "motion_stop"

# Input
input_datetime:
  loft_auxiliary_on:
    name: Faretti On
    has_date: false
    has_time: true
  loft_auxiliary_off:
    name: Faretti Off
    has_date: false
    has_time: true

input_select:
  radio_chromecast:
    name: Speakers
    icon: mdi:speaker-wireless
    options:
      - Mansarda
      - Salotto
      - Taverna
  radio_station:
    name: Stazione Radio
    icon: mdi:radio
    options:
      - Radio 105
      - Virgin Radio
  loft_studio_lamps:
    name: Bottone
    icon: mdi:lamps
    options:
      - Studio
      - Scaffale
      - Faretti
  loft_discoball_song:
    name: Traccia
    icon: mdi:music
    options:
      - Bee Gees - Stayin Alive
      - Engelwood - Crystal Dolphin
      - Sofi Tukker - Batshit
      - Star Wars - The Imperial March
      - The Drifters feat - White Christmas

input_number:
  radio_volume:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05
    initial: 0.2
  night:
    name: Night
    min: 0
    max: 1

input_boolean:
  radio_activate:
    name: Play
    initial: off
    icon: mdi:play
  loft_discoball_activate:
    name: Party Time
    initial: off
    icon: mdi:music-note
# Plant
#plant:
#  grande:
#    sensors:
#      moisture: sensor.flora1_moisture
#      battery: sensor.flora1_battery
#      temperature: sensor.flora1_temperature
#      conductivity: sensor.flora1_conductivity
#      brightness: sensor.flora1_light_intensity
#    min_battery: 10
#  piccolo:
#    sensors:
#      moisture: sensor.flora2_moisture
#      battery: sensor.flora2_battery
#      temperature: sensor.flora2_temperature
#      conductivity: sensor.flora2_conductivity
#      brightness: sensor.flora2_light_intensity
#    min_battery: 10
