# Main Configuration File

# Homeassistant
homeassistant:
  name: "Home CDB"
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  country: IT
  time_zone: Europe/Rome
  external_url: !secret home_eurl
  internal_url: !secret home_iurl

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 75

# Basic Functionality
bluetooth:
#cloud:
config:
counter:
dhcp:
energy:
frontend:
media_source:
mobile_app:
my:
person:
ssdp:
stream:
system_health:
tag:
timer:
usb:
webhook:
zeroconf:

# Http
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.252
    - 192.168.1.253

# Split Config 1
recorder: !include recorder.yaml
history:
logbook:

# Split Config 2
automation: !include_dir_merge_list automation
climate: !include climates.yaml
mqtt: !include mqtt.yaml
sensor: !include_dir_merge_list sensor
script: !include_dir_merge_named ./script
switch: !include_dir_merge_list switch
#scene:

# Garmin Connect
group:
  garmin:
    name: Garmin
    entities:
      - switch.shelly1_5551cc

# Utility Meter
utility_meter:
  home_consumption_daily:
    source: sensor.home_consumption
    name: Consumo Casa Giornaliero
    cycle: daily
  home_consumption_monthly:
    source: sensor.home_consumption
    name: Consumo Casa Mensile
    cycle: monthly
  tavern_and_garage_consumption_daily:
    source: sensor.tavern_and_garage_consumption
    name: Consumo Taverna&Garage Giornaliero
    cycle: daily
  tavern_and_garage_consumption_monthly:
    source: sensor.tavern_and_garage_consumption
    name: Consumo Taverna&Garage Mensile
    cycle: monthly
  loft_and_main_consumption_daily:
    source: sensor.loft_and_main_consumption
    name: Consumo Loft&Main Giornaliero
    cycle: daily
  loft_and_main_consumption_monthly:
    source: sensor.loft_and_main_consumption
    name: Consumo Loft&Main Mensile
    cycle: monthly

# Driver & Camera
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

# Weather
sun:

# Google Assistant
google_assistant:
  project_id: jarvis-59028
  service_account: !include jarvis-59028-6b0d0b5a50ba.json
  report_state: true
  expose_by_default: false
  exposed_domains:
    - light
    - climate
    - switch
  entity_config:
    climate.loft:
      name: Termostato Mansarda
      expose: true
    climate.main:
      name: Termostato Padronale
      expose: true
    input_boolean.radio_activate:
      name: Radio
      expose: true
    input_boolean.loft_discoball_activate:
      name: Party
      expose: true
    light.shellyvintage_3494546ef990:
      name: Poltrona
      expose: True
    switch.shellyswitch25_c45bbe756bc1_channel_1:
      name: Ingresso
      expose: true
    switch.shellyswitch25_c45bbe756bc1_channel_2:
      name: Cucina
      expose: true
    switch.shellyswitch25_c45bbe763805_channel_2:
      name: Salotto
      expose: true
    switch.shelly1pm_84cca8a855b6:
      name: Aba
      expose: true
    switch.shellyswitch25_c45bbe763805_channel_1:
      name: Camera
      expose: true
    switch.shellyswitch_55c794_channel_2:
      name: Faretti
      expose: true
    switch.shellyswitch_55c794_channel_1:
      name: Studio
      expose: true
    switch.shelly1pm_e89f6d86855c:
      name: Albero
      expose: true
    switch.shellyswitch_55c39a_channel_2:
      name: Tana
      expose: true
    switch.shellyswitch_55c39a_channel_1:
      name: Cielo
      expose: true
    switch.shellyswitch_559384_channel_2:
      name: Scaffale
      expose: true
    sensor.shellyswitch_559384_power:
      name: DiscoBall
      expose: true
    switch.shelly1_5551cc:
      name: Cancello
      expose: true

# TTS
tts:
  - platform: google_translate
    service_name: google_say
    language: it

# Input
input_datetime:
  loft_auxiliary_on:
    name: Faretti On
    has_date: false
    has_time: true
  loft_auxiliary_off:
    name: Faretti Off
    has_date: false
    has_time: true

input_select:
  radio_chromecast:
    name: Speakers
    icon: mdi:speaker-wireless
    options:
      - Mansarda
      - Salotto
      - Taverna
  radio_station:
    name: Stazione Radio
    icon: mdi:radio
    options:
      - Radio 105
      - Virgin Radio
  c510w1_camera:
    name: Preset
    icon: mdi:camera-marker-outline
    options:
      - Parcheggio
      - Taverna
      - Padronale
  loft_studio_lamps:
    name: Bottone
    icon: mdi:lamps
    options:
      - Studio
      - Scaffale
      - Faretti
  loft_discoball_song:
    name: Traccia
    icon: mdi:music
    options:
      - Bee Gees - Stayin Alive
      - Engelwood - Crystal Dolphin
      - Sofi Tukker - Batshit
      - Star Wars - The Imperial March
      - The Drifters feat - White Christmas

input_number:
  radio_volume:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05
    initial: 0.2
  night:
    name: Night
    min: 0
    max: 1

input_boolean:
  radio_activate:
    name: Play
    initial: off
    icon: mdi:play
  loft_discoball_activate:
    name: Party Time
    initial: off
    icon: mdi:music-note
