# Broadlink

# Broadlink Mini 3
- platform: broadlink
  mac: 'c8:f7:42:17:45:20'
  host: 192.168.1.130
  switches:
    - name: mitsubishi
      command_on: 'JgDmAG85DisNLAwQDQ8NEAwrDhAMDw0sDSoOEAwsDQ8NEAotDisNEA0rDSsLEgoSDSsODgsSCy0NEAwPDg8NDwwRDBANDwwQCxIMEAwPDRALEgwPDQ8NEAwRDCsNDw4OCi8NEAouDSsOKg4PDQ8NEAwQDQ8NDwsuDSoOKw4qDhAMEAoSDQ8LEgoSDQ8MLQwsDCwNDw0QDA8ODw0PDRAMEA0PDQ8MEQwQChILEQ0PDRAMEAwQCxENDw0QDBEKEgwPDBEMEAoSDQ8NEAwQChIKEg0QDBAKEQowDCwMEA0QChENDw0QDQ8KAA0FAAA='
      command_off: 'JgDmAHA4DisNKw0QDBAODQ4rDg8ODg0rDioNEQwrDRANDw4qDisODQ4rDioNEA0PDSsODw0PDioNEA0PDg8MDg4RDA8ODg0QDBAODQ4PDRANDw0PDRAMEA0PDQ4NEQwQDSoODw0rDisNKw0PDRANDg4QDA8ODw0rDSsPKg0rDg4NEQwPDQ8ODg0RDA8NKw4qDSwODg4PDQ8NDw0QDQ4NEQwPDRAMDw0RDA8NDw4PDQ8NDw0QDBANDw0ODg8NEA0PDQ4NEA0PDQ8ODw0QDA8NEAwPDRAODQ4rDSsOKw0rDisOKg0sDSsOAA0FAAA='