# Switch: Shelly (MQTT)

# Shelly1: Loft Thermostat (Toggle)
- platform: mqtt
  name: loft_thermostat
  state_topic: "shellies/shelly1-555FCE/relay/0"
  command_topic: "shellies/shelly1-555FCE/relay/0/command"
  payload_on: "on"
  payload_off: "off"

# Shelly1PM: Loft Air Cooler (Toggle)
- platform: mqtt
  name: loft_aircooler
  state_topic: "shellies/shelly1pm-609CA4/relay/0"
  command_topic: "shellies/shelly1pm-609CA4/relay/0/command"
  payload_on: "on"
  payload_off: "off"

# Shelly2: Loft Den Main (Momentary)
- platform: mqtt
  name: loft_den_main
  state_topic: "shellies/shellyswitch-55C39A/relay/1"
  command_topic: "shellies/shellyswitch-55C39A/relay/1/command"
  payload_on: "on"
  payload_off: "off"

# Shelly2: Loft Den Auxiliary (Momentary)
- platform: mqtt
  name: loft_den_auxiliary
  state_topic: "shellies/shellyswitch-55C39A/relay/0"
  command_topic: "shellies/shellyswitch-55C39A/relay/0/command"
  payload_on: "on"
  payload_off: "off"

# Shelly2: Lofr Studio Main (Momentary)
- platform: mqtt
  name: loft_studio_main
  state_topic: "shellies/shellyswitch-55C794/relay/0"
  command_topic: "shellies/shellyswitch-55C794/relay/0/command"
  payload_on: "on"
  payload_off: "off"

# Shelly2: Loft Studio Position (Momentary)
- platform: mqtt
  name: loft_studio_auxiliary
  state_topic: "shellies/shellyswitch-55C794/relay/1"
  command_topic: "shellies/shellyswitch-55C794/relay/1/command"
  payload_on: "on"
  payload_off: "off"

# Shelly2: Loft Studio Shelf (Momentary)
- platform: mqtt
  name: loft_studio_shelf
  state_topic: "shellies/shellyswitch-559384/relay/1"
  command_topic: "shellies/shellyswitch-559384/relay/1/command"
  payload_on: "on"
  payload_off: "off"

# Shelly2: Loft Studio Discoball (Momentary)
- platform: mqtt
  name: loft_studio_discoball
  state_topic: "shellies/shellyswitch-559384/relay/0"
  command_topic: "shellies/shellyswitch-559384/relay/0/command"
  payload_on: "on"
  payload_off: "off"

# Shelly2.5: Main Entrance (Momentary)
- platform: mqtt
  name: main_entrance
  state_topic: "shellies/shellyswitch25-740859/relay/0"
  command_topic: "shellies/shellyswitch25-740859/relay/0/command"
  payload_on: "on"
  payload_off: "off"

# Shelly2.5: Main Kitchen (Momentary)
- platform: mqtt
  name: main_kitchen
  state_topic: "shellies/shellyswitch25-740859/relay/1"
  command_topic: "shellies/shellyswitch25-740859/relay/1/command"
  payload_on: "on"
  payload_off: "off"

# Shelly2.5: Main Bedroom (Momentary)
- platform: mqtt
  name: main_bedroom
  state_topic: "shellies/shellyswitch25-740826/relay/0"
  command_topic: "shellies/shellyswitch25-740826/relay/0/command"
  payload_on: "on"
  payload_off: "off"

# Shelly2.5: Main Living (Momentary)
- platform: mqtt
  name: main_living
  state_topic: "shellies/shellyswitch25-740826/relay/1"
  command_topic: "shellies/shellyswitch25-740826/relay/1/command"
  payload_on: "on"
  payload_off: "off"

# Shelly1: Main Gate (Momentary/Detached)
- platform: mqtt
  name: main_gate
  state_topic: "shellies/shelly1-5551CC/relay/0"
  command_topic: "shellies/shelly1-5551CC/relay/0/command"
  payload_on: "on"
  payload_off: "off"

# Shelly1: Main Thermostat (Toggle)
- platform: mqtt
  name: main_thermostat
  state_topic: "shellies/shelly1-3C71BF2C02AE/relay/0"
  command_topic: "shellies/shelly1-3C71BF2C02AE/relay/0/command"
  payload_on: "on"
  payload_off: "off"