# Sensor: Climate

# CFR TOS11000046
- platform: cfr
  name: cfr_montopoli_temperature
  station: TOS11000046
  type: termo
- platform: cfr
  name: cfr_montopoli_wind
  station: TOS11000046
  type: anemo
- platform: cfr
  name: cfr_montopoli_humidity
  station: TOS11000046
  type: igro
- platform: cfr
  name: cfr_montopoli_pluvio
  station: TOS11000046
  type: pluvio

# CFR TOS01005181
- platform: cfr
  name: cfr_pontedera_idro
  station: TOS01005181
  type: idro

# CFR TOS01005001
- platform: cfr
  name: cfr_fucecchio_idro
  station: TOS01005001
  type: idro

# Delta CFR/Sensor
- platform: template
  sensors:
    cfr_esterno_deltatemperature:
      unit_of_measurement: "°C"
      icon_template: mdi:thermometer
      value_template: >
        {{ (states.sensor.cfr_montopoli_temperature.state|float - states.sensor.loft_external_climate_temperature.state|float)|round(2) }}
    cfr_esterno_deltahumidity:
      unit_of_measurement: "%"
      icon_template: mid:water-percent
      value_template: >
        {{ (states.sensor.cfr_montopoli_humidity.state|float - states.sensor.loft_external_climate_humidity.state|float)|round(2) }}

# Loft Relevant Temperature
- platform: template
  sensors:
    loft_relevant_temperature:
      unit_of_measurement: "°C"
      value_template: >
        {% if 8 <= strptime(states('sensor.time'), "%H:%M").hour < 23 %} {{states.sensor.loft_studio_climate_temperature.state}}
        {% else %} {{states.sensor.loft_tana_climate_temperature.state}}
        {% endif %}
    loft_relevant_text:
      icon_template: mdi:map-clock
      value_template: >
        {% if 8 <= strptime(states('sensor.time'), "%H:%M").hour < 23 %} Studio
        {% else %} Tana
        {% endif %}
