# Sensor: Shelly

# ShellyEM: Electical MainFrame (Template/Integration)
- platform: template
  sensors:
    home_power:
      unit_of_measurement: "W"
      value_template: >
        {{ (states("sensor.shellyem_244cab431c8c_channel_1_power")|float + states("sensor.shellyem_244cab431c8c_channel_2_power")|float) | round(2) }}
- platform: integration
  source: sensor.shellyem_244cab431c8c_channel_1_power
  name: loft_and_main_consumption
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.shellyem_244cab431c8c_channel_2_power
  name: tavern_and_garage_consumption
  unit_prefix: k
  round: 2
- platform: integration
  source: sensor.home_power
  name: home_consumption
  unit_prefix: k
  round: 2
