# Sensor: System Monitor

# System Usage
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot

# System Temperature
- platform: mqtt
  name: nuc_temperature
  state_topic: "system_monitor/temperature"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(2)}}"
