# Sensor: WemosD1 (MQTT)

# WemosA: Water Softener
- platform: mqtt
  name: main_softener
  state_topic: "tele/watersoftener/SENSOR"
  unit_of_measurement: "cm"
  value_template: "{{ value_json.SR04.Distance }}"

# WemosA: Water Softener Percentage
- platform: template
  sensors:
    main_softener_percentage:
      unit_of_measurement: "%"
      value_template: "{{ ((states('sensor.main_softener')|float * -2.86 + 243) |round(1)) }}"
      icon_template: mdi:hydraulic-oil-temperature
