# Sensor: WemosD1

# WemosA: Water Softener Percentage
- platform: template
  sensors:
    main_softener_percentage:
      unit_of_measurement: "%"
      value_template: "{{ ((states('sensor.main_softener')|float * -2.86 + 243) |round(1)) }}"
      icon_template: mdi:hydraulic-oil-temperature
