# Sensor: WemosD1 (MQTT)

# WemosA: Water Softener Percentage
- platform: template
  sensors:
    main_softener_percentage:
      unit_of_measurement: "%"
      value_template: "{{ ((-2.86*states('sensor.watersoftener_sr04_distance')|float + 243)|round(1))|max(0)|min(100) }}"
      icon_template: mdi:hydraulic-oil-temperature