# Automation: Camera Control

# Camera Preset
- alias: c510w1_preset
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_select.c510w1_camera
  action:
    - service: onvif.ptz
      target:
        device_id: e272b139af0a51fd2d86f2a1ce249c7d
      data:
        speed: 1
        continuous_duration: 0.5
        move_mode: GotoPreset
        preset: >
          {% if is_state('input_select.c510w1_camera', 'Parcheggio') %} 1
          {% elif is_state('input_select.c510w1_camera', 'Taverna') %} 2
          {% elif is_state('input_select.c510w1_camera', 'Padronale') %} 3
          {% endif %}
