# Automation: Climate

# External vs Loft Temperature
- alias: loft_climate_deltapositive
  initial_state: on
  trigger:
    - platform: template
      value_template: "{{ states.sensor.cfr_montopoli_temperature.state|float + 2 > states.sensor['0x00158d000346487a_temperature'].attributes.temperature|float }}"
  action:
    - service: notify.mobile_app_samsung_s7e
      data:
        title: "Confronto Temperatura"
        message: "Fuori ci sono 2°C in più che in mansarda!"
        data:
          tag: temperatura

- alias: loft_climate_deltanegative
  initial_state: on
  trigger:
    - platform: template
      value_template: "{{ states.sensor.cfr_montopoli_temperature.state|float + 2 < states.sensor['0x00158d000346487a_temperature'].attributes.temperature|float }}"
  action:
    - service: notify.mobile_app_samsung_s7e
      data:
        title: "Confronto Temperatura"
        message: "Fuori ci sono 2°C in meno che in mansarda!"
        data:
          tag: temperatura

# Climate Loft Set-Point
- alias: loft_climate_setpoint_day
  initial_state: on
  trigger:
    - platform: time
      at: '07:00:00'
  action: 
    - service: climate.set_temperature
      data:
        entity_id: climate.loft
        temperature: 19.5
        # Estiva: 25.5
    - service: notify.mobile_app_samsung_s7e
      data:
        title: "Climate Loft"
        message: "Temperatura giorno (19.5°C) in vigore!"
        data:
          tag: Termostato_Loft

- alias: loft_climate_setpoint_night
  initial_state: on
  trigger:
    - platform: time
      at: '23:30:00'
  action: 
    - service: climate.set_temperature
      data:
        entity_id: climate.loft
        temperature: 18
        # Estivo 26
    - service: notify.mobile_app_samsung_s7e
      data:
        title: "Climate Loft"
        message: "Temperatura notte (18°C) entrata in vigore!"
        data:
          tag: Termostato_Loft

# Climate Main Set-Point
- alias: main_climate_setpoint_night
  initial_state: on
  trigger:
    - platform: time
      at: '23:30:00'
  action: 
    - service: climate.set_temperature
      data:
        entity_id: climate.main
        temperature: 17
        # Estivo 26
    - service: notify.mobile_app_samsung_s7e
      data:
        title: "Piattaforma Climate"
        message: "Temperatura notte (17°C) entrata in vigore!"
        data:
          tag: Termostato_Main
