# Automation: Climate

# External vs Loft Temperature
- alias: loft_climate_deltapositive
  initial_state: on
  trigger:
    - platform: template
      value_template: "{{ states.sensor.cfr_montopoli_temperature.state|float + 2 > states.sensor['0x00158d000346487a_temperature'].attributes.temperature|float }}"
  action:
    - service: notify.mobile_app_samsung_s7e
      data:
        title: "Confronto Temperatura"
        message: "Fuori ci sono 2°C in più che in mansarda!"
        data:
          tag: temperatura

- alias: loft_climate_deltanegative
  initial_state: on
  trigger:
    - platform: template
      value_template: "{{ states.sensor.cfr_montopoli_temperature.state|float + 2 < states.sensor['0x00158d000346487a_temperature'].attributes.temperature|float }}"
  action:
    - service: notify.mobile_app_samsung_s7e
      data:
        title: "Confronto Temperatura"
        message: "Fuori ci sono 2°C in meno che in mansarda!"
        data:
          tag: temperatura

# Climate Loft Set-Point
- alias: loft_climate_setpoint_day
  initial_state: on
  trigger:
    - platform: time
      at: '07:00:00'
  action: 
    - service: climate.set_temperature
      data:
        entity_id: climate.loft
        temperature: 26
        # Invernale: 19.5
    - service: notify.mobile_app_samsung_s7e
      data:
        title: "Climate Loft"
        message: "Temperatura giorno (26°C) in vigore!"
        data:
          tag: Termostato_Loft

- alias: loft_climate_setpoint_night
  initial_state: on
  trigger:
    - platform: time
      at: '23:30:00'
  action: 
    - service: climate.set_temperature
      data:
        entity_id: climate.loft
        temperature: 26
        # Invernale 18
    - service: notify.mobile_app_samsung_s7e
      data:
        title: "Climate Loft"
        message: "Temperatura notte (26°C) entrata in vigore!"
        data:
          tag: Termostato_Loft

# Climate Loft Cooler Check
- alias: loft_climate_cooler_check_on
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.mitsubishi
      to: 'on'
  action:
    - delay:
        seconds: 5
    - service: homeassistant.turn_on
      entity_id: switch.mitsubishi
    - delay:
        seconds: 5
    - service: homeassistant.turn_on
      entity_id: switch.mitsubishi    

- alias: loft_climate_cooler_check_off
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.mitsubishi
      to: 'off'
  action:
    - delay:
        seconds: 5
    - service: homeassistant.turn_off
      entity_id: switch.mitsubishi
    - delay:
        seconds: 5
    - service: homeassistant.turn_off
      entity_id: switch.mitsubishi    

# Climate Main Set-Point
- alias: main_climate_setpoint_night
  initial_state: on
  trigger:
    - platform: time
      at: '23:30:00'
  action: 
    - service: climate.set_temperature
      data:
        entity_id: climate.main
        temperature: 17
        # Estivo 26
    - service: notify.mobile_app_samsung_s7e
      data:
        title: "Piattaforma Climate"
        message: "Temperatura notte (17°C) entrata in vigore!"
        data:
          tag: Termostato_Main
