# Automation: Climate

# External vs Loft Temperature
- alias: loft_climate_deltapositive
  initial_state: true
  trigger:
    - platform: template
      value_template: "{{ states.sensor.loft_external_climate_temperature.state|float + 2 > states.sensor.loft_relevant_temperature.state|float }}"
  action:
    - service: notify.mobile_app_s22plus
      data:
        title: "Confronto Temperatura"
        message: "Fuori ci sono 2°C in più che in mansarda!"
        data:
          tag: temperatura

- alias: loft_climate_deltanegative
  initial_state: true
  trigger:
    - platform: template
      value_template: "{{ states.sensor.loft_external_climate_temperature.state|float + 2 < states.sensor.loft_relevant_temperature.state|float }}"
  action:
    - service: notify.mobile_app_s22plus
      data:
        title: "Confronto Temperatura"
        message: "Fuori ci sono 2°C in meno che in mansarda!"
        data:
          tag: temperatura

# Climate Loft Set-Point
# Season: temperature (day); temperature (night);
# Winter: 19.5; 18 [17.5; 16.5]
# Summer: 26.5; 26.5
- alias: loft_climate_setpoint_day
  initial_state: true
  trigger:
    - platform: time
      at: "08:00:00"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.loft
        temperature: 26.5
    - service: notify.mobile_app_s22plus
      data:
        title: "Climate Loft"
        message: "Temperatura giorno (26°C) in vigore!"
        data:
          tag: Termostato_Loft

- alias: loft_climate_setpoint_night
  initial_state: true
  trigger:
    - platform: time
      at: "23:00:00"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.loft
        temperature: 26.5
    - service: notify.mobile_app_s22plus
      data:
        title: "Climate Loft"
        message: "Temperatura notte (26°C) entrata in vigore!"
        data:
          tag: Termostato_Loft

# Climate Loft Cooler Check
- alias: loft_climate_cooler_check_on
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.mitsubishi
      to: "on"
  action:
    - delay:
        seconds: 5
    - service: homeassistant.turn_on
      entity_id: switch.mitsubishi
    - delay:
        seconds: 5
    - service: homeassistant.turn_on
      entity_id: switch.mitsubishi

- alias: loft_climate_cooler_check_off
  initial_state: on
  trigger:
    - platform: state
      entity_id: switch.mitsubishi
      to: "off"
  action:
    - delay:
        seconds: 5
    - service: homeassistant.turn_off
      entity_id: switch.mitsubishi
    - delay:
        seconds: 5
    - service: homeassistant.turn_off
      entity_id: switch.mitsubishi

# Climate Main Set-Point
- alias: main_climate_setpoint_day
  initial_state: true
  trigger:
    - platform: time
      at: "08:00:00"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.main
        temperature: 17.5
    - service: notify.mobile_app_j7_l
      data:
        title: "Climate Main"
        message: "Temperatura giorno (17.5°C) in vigore!"
        data:
          tag: Termostato_Main

- alias: main_climate_setpoint_night
  initial_state: true
  trigger:
    - platform: time
      at: "23:00:00"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.main
        temperature: 16.5
    - service: notify.mobile_app_j7_l
      data:
        title: "Climate Main"
        message: "Temperatura notte (16.5°C) entrata in vigore!"
        data:
          tag: Termostato_Main
