# Automation: Home Network

# K4 Online
- alias: k4_online
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.k4  
      to: "on"
    - platform: state
      entity_id: binary_sensor.k4  
      to: "off"
  action:
    - service: notify.mobile_app_samsung_s7e
      data:
        title: "Computer K4"
        message: >
          K4 è {{ trigger.to_state.state }}line!
        data:
          tag: k4

# K9 Online
- alias: k9_online
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.k9 
      to: "on"
    - platform: state
      entity_id: binary_sensor.k9  
      to: "off"
  action:
    - service: notify.mobile_app_samsung_s7e
      data:
        title: "Computer K9"
        message: >
          K9 è {{ trigger.to_state.state }}line!
        data:
          tag: k9

# Dell Online          
#- alias: dell_online
#  initial_state: on
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.dell
#      to: 'on'
#  action:
#    - service: notify.mobile_app_samsung_j7_g
#      data:
#        title: "Computer Dell Online"
#        message: "HomeAssistant ti augura buon lavoro!"
#        data:
#          tag: Dell      
#    - service:  media_player.volume_set
#      entity_id: media_player.mansarda
#      data:
#        volume_level: 0.2
#    - service: media_player.play_media
#      entity_id: media_player.mansarda
#      data_template:
#        media_content_id: https://home.ziotitanok.duckdns.org/local/music/star_wars-imperial_march.mp3
#        media_content_type: audio/mp3



