# Automation: Home Network

# K6 Online
- alias: k6_online
  initial_state: true
  triggers:
    - trigger: state
      entity_id: binary_sensor.k6
      to: "on"
    - trigger: state
      entity_id: binary_sensor.k6
      to: "off"
  actions:
    - action: notify.mobile_app_s22plus
      data:
        title: "Computer K6"
        message: >
          K6 è {{ trigger.to_state.state }}line!
        data:
          tag: k6

# K7 Online
- alias: k7_online
  initial_state: true
  triggers:
    - trigger: state
      entity_id: binary_sensor.k7
      to: "on"
    - trigger: state
      entity_id: binary_sensor.k7
      to: "off"
  actions:
    - action: notify.mobile_app_s22plus
      data:
        title: "Computer K7"
        message: >
          K7 è {{ trigger.to_state.state }}line!
        data:
          tag: k7
