# Automation: Discoball

# Discoball On
- alias: loft_studio_discoball_on
  initial_state: true
  triggers:
    - trigger: state
      entity_id: input_boolean.loft_discoball_activate
      to: "on"
  actions:
    - action: switch.turn_on
      entity_id: switch.shellyswitch_559384_channel_1
    - action: media_player.volume_set
      entity_id: media_player.loft
      data:
        volume_level: 0.2
    - action: media_player.play_media
      entity_id: media_player.loft
      data_template:
        media_content_id: >
          {% if is_state('input_select.loft_discoball_song', 'Bee Gees - Stayin Alive') %} media-source://media_source/local/bee_gees-stayin_alive.mp3
          {% elif is_state('input_select.loft_discoball_song', 'Engelwood - Crystal Dolphin') %} media-source://media_source/local/engelwood-crystal_dolphin.mp3
          {% elif is_state('input_select.loft_discoball_song', 'Sofi Tukker - Batshit') %} media-source://media_source/local/sofi_tukker-batshit.mp3
          {% elif is_state('input_select.loft_discoball_song', 'Star Wars - The Imperial March') %} media-source://media_source/local/star_wars-imperial_march.mp3
          {% elif is_state('input_select.loft_discoball_song', 'The Drifters feat - White Christmas') %} media-source://media_source/local/the_drifters_feat-white_christmas.mp3
          {% endif %}
        media_content_type: audio/mp3

# Discoball Off
- alias: loft_studio_discoball_off
  initial_state: true
  triggers:
    - trigger: state
      entity_id: input_boolean.loft_discoball_activate
      to: "off"
  actions:
    - action: switch.turn_off
      entity_id: switch.shellyswitch_559384_channel_1
    - action: media_player.turn_off
      data:
        entity_id: media_player.loft
