# Automation: Gate Control

# Pulse Auto-Off
- alias: main_gate_management
  initial_state: true
  trigger:
    - platform: state
      entity_id: switch.shelly1_5551cc
      to: "on"
      for:
        seconds: 1
  action:
    - service: homeassistant.turn_off
      entity_id: switch.shelly1_5551cc
    - service: notify.mobile_app_redmi_6a
      data:
        title: "Gate"
        message: "Cancello in azione!"
        data:
          tag: Gate

# Gate Tag NFC
- alias: main_gate_nfc
  initial_state: true
  trigger:
    - platform: tag
      tag_id: 34236b65-3737-4d32-bc79-1b8fe4f479d7
    - platform: tag
      tag_id: 42799d6f-c3bf-4bb5-9b4e-b6df30fb23aa
  action:
    - service: homeassistant.turn_on
      entity_id: switch.shelly1_5551cc
