# Automation: Gate Control

# Pulse Auto-Off
- alias: main_gate_management
  initial_state: true
  triggers:
    - trigger: state
      entity_id: switch.shelly1_5551cc
      to: "on"
      for:
        seconds: 2
  actions:
    - action: switch.turn_off
      entity_id: switch.shelly1_5551cc
    - action: notify.mobile_app_s22plus
      data:
        title: "Gate"
        message: "Cancello in azione!"
        data:
          tag: Gate

# Gate Tag NFC Clio
- alias: main_gate_nfc_clio
  initial_state: true
  triggers:
    - trigger: tag
      tag_id: 72003416-c321-4f47-af6f-f5c66cb16400
  actions:
    - action: switch.turn_on
      entity_id: switch.shelly1_5551cc
