# Automation: Light

# Loft Studio Shelf Auto On
- alias: loft_studio_shelf_on
  initial_state: true
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.loft_studio_shelf

# Loft Studio Shelf Auto Off
- alias: loft_studio_shelf_off
  initial_state: true
  trigger:
    - platform: time
      at: '22:30:00'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.loft_studio_shelf

# Loft Studio Portable Auto On
- alias: loft_studio_portable_on
  initial_state: true
  trigger:
    - platform: time
      at: '08:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.loft_studio_portable

# Loft Studio Portable Auto Off
- alias: loft_studio_portable_off
  initial_state: true
  trigger:
    - platform: time
      at: '23:55:00'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.loft_studio_portable

# Loft Studio Auxiliary Auto On
- alias: loft_studio_auxiliary_on
  initial_state: false
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.loft_auxiliary_on.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  action:
    - service: homeassistant.turn_on
      entity_id: switch.loft_studio_auxiliary

# Loft Studio Auxiliary Auto Off
- alias: loft_studio_auxiliary_off
  initial_state: false
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.loft_auxiliary_off.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  action:
    - service: homeassistant.turn_off
      entity_id: switch.loft_studio_auxiliary
