# Automation: Motion

- alias: loft_motion
  initial_state: true
  triggers:
    - trigger: state
      entity_id: binary_sensor.loft_studio_pir_status
      to: "on"
  actions:
    - action: notify.mobile_app_s22plus
      data:
        title: "Rilevato Movimento"
        message: "E' stato rilevato un movimento in mansarda!"
        data:
          tag: Movement
