# Automation: House Main Power Control

# Check Over Power
- alias: home_power_check
  initial_state: on
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_power
      above: 3000
      for: "00:00:05"
  action:
    - service: notify.mobile_app_samsung_s7e
      data:
        title: "Check Potenza"
        message: "E' stata superata la soglia dei 3kW!"
        data:
          tag: Power