# Automation: House Main Power Control

# Check Over Power
- alias: home_power_check_100s
  initial_state: true
  triggers:
    - trigger: numeric_state
      entity_id: sensor.home_power
      above: 3300
      for: "00:01:30"
  action:
    - action: notify.mobile_app_s22plus
      data:
        title: "Check Potenza"
        message: "E' stata superata la soglia dei 3.3kW per 100s!"
        data:
          tag: Power
    - action: tts.google_say
      entity_id: media_player.loft
      data:
        message: "Superata la soglia di 3.3 kilowatt per 100 secondi!"
    - action: tts.google_say
      entity_id: media_player.main
      data:
        message: "Superata la soglia di 3.3 kilowatt per 100 secondi!"
