# Automation: Service and System

# Reboot Notification
- alias: pi_reboot
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.mobile_app_s7_nico
      data:
        title: "Homeassistant"
        message: "Sistema riavviato con successo."
        data:
          tag: Sistema
    - service: tts.google_say
      entity_id: media_player.loft
      data:
        message: "Riavvio di sistema completato con successo."

# Day/Night Graph Cicle
- alias: pi_night
  initial_state: true
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.night
        value: 1

- alias: pi_day
  initial_state: true
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.night
        value: 0