# Automation: Service and System

# Reboot Notification
- alias: ha_reboot
  initial_state: true
  triggers:
    - trigger: homeassistant
      event: start
  actions:
    - action: notify.mobile_app_s22plus
      data:
        title: "Homeassistant"
        message: "Sistema riavviato con successo."
        data:
          tag: Sistema
    - action: tts.google_say
      entity_id: media_player.loft
      data:
        message: "Riavvio di sistema completato con successo."

# Ip Change Notification
- alias: ip_change
  initial_state: true
  triggers:
    - trigger: homeassistant
      event: start
    - trigger: state
      entity_id: sensor.fritz_box_7530_ax_ip_esterno
  actions:
    - action: notify.mobile_app_s22plus
      data:
        title: "Rete"
        message: "Il nuovo indirizzo IP è {{ states.sensor.fritz_box_7530_ax_ip_esterno.state }}"
  mode: single

# Day/Night Graph Cicle
- alias: home_night
  initial_state: true
  triggers:
    - trigger: sun
      event: sunset
  actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.night
        value: 1

- alias: home_day
  initial_state: true
  triggers:
    - trigger: sun
      event: sunrise
  actions:
    - action: input_number.set_value
      data:
        entity_id: input_number.night
        value: 0
