# Automation: Service and System

# Reboot Notification
- alias: ha_reboot
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.mobile_app_s22plus
      data:
        title: "Homeassistant"
        message: "Sistema riavviato con successo."
        data:
          tag: Sistema
    - service: tts.google_say
      entity_id: media_player.loft
      data:
        message: "Riavvio di sistema completato con successo."

# Ip Change Notification
- alias: ip_change
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.external_ip
  #  condition:
  #    - condition: template
  #      value_template: '"{{ trigger.to_state.state != ''None'' }}"'
  action:
    - service: notify.mobile_app_s22plus
      data:
        title: "Rete"
        message: "Il nuovo indirizzo IP è {{ states.sensor.external_ip.state }}"
  mode: single

# Day/Night Graph Cicle
- alias: home_night
  initial_state: true
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.night
        value: 1

- alias: home_day
  initial_state: true
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.night
        value: 0
