# Automation: Trafdi Remote Kit

# On/Off
- alias: loft_trafdi_toggle
  initial_state: true
  triggers:
    - device_id: ba8962c0419d032ddf614886117b58ef
      domain: zha
      trigger: device
      type: remote_button_short_press
      subtype: turn_on
  actions:
    - action: homeassistant.toggle
      data_template:
        entity_id: >
          {% if is_state('input_select.loft_studio_lamps', 'Studio') %} switch.shellyswitch_55c794_channel_1
          {% elif is_state('input_select.loft_studio_lamps', 'Faretti') %} switch.shellyswitch_55c794_channel_2
          {% elif is_state('input_select.loft_studio_lamps', 'Scaffale') %} switch.shellyswitch_559384_channel_2
          {% endif %}

# Dimmer
- alias: loft_trafdi_dimup
  initial_state: true
  triggers:
    - device_id: ba8962c0419d032ddf614886117b58ef
      domain: zha
      trigger: device
      type: remote_button_short_press
      subtype: dim_up
  condition:
    - condition: state
      entity_id: switch.shellyswitch_55c794_channel_1
      state: "on"
  actions:
    - device_id: 0ef8dda1e879f241e9ad03f16a40e6da
      domain: light
      entity_id: light.loft_studio_wallexternal_status
      type: brightness_increase
    - device_id: 74a079a4a2b46ee1fe86d8081a12db80
      domain: light
      entity_id: light.loft_studio_wallinternal_status
      type: brightness_increase

- alias: loft_trafdi_dimdown
  initial_state: true
  triggers:
    - device_id: ba8962c0419d032ddf614886117b58ef
      domain: zha
      trigger: device
      type: remote_button_short_press
      subtype: dim_down
  condition:
    - condition: state
      entity_id: switch.shellyswitch_55c794_channel_1
      state: "on"
  actions:
    - device_id: 0ef8dda1e879f241e9ad03f16a40e6da
      domain: light
      entity_id: light.loft_studio_wallexternal_status
      type: brightness_decrease
    - device_id: 74a079a4a2b46ee1fe86d8081a12db80
      domain: light
      entity_id: light.loft_studio_wallinternal_status
      type: brightness_decrease

# Light Selection
- alias: loft_trafdi_right
  initial_state: true
  triggers:
    - device_id: ba8962c0419d032ddf614886117b58ef
      domain: zha
      trigger: device
      type: remote_button_short_press
      subtype: right
  actions:
    - action: input_select.select_next
      entity_id: input_select.loft_studio_lamps

- alias: loft_trafdi_left
  initial_state: true
  triggers:
    - device_id: ba8962c0419d032ddf614886117b58ef
      domain: zha
      trigger: device
      type: remote_button_short_press
      subtype: left
  actions:
    - action: input_select.select_previous
      entity_id: input_select.loft_studio_lamps
